### PR TITLE
IMP add variable to nexus-default.properties

### PR DESCRIPTION
**Pull request by OliverJurkschat**

### CODE REVIEW

**Comment by OliverJurkschat** [comment]
Hey Kok-Yan Lo,
i wanted to setup your image together with traefik on a subpath. I discovered that the image does not regard the NEXUS_CONTEXT env-variable  defined in my docker-compose.yml. So i tweaked it a little and now it works. Maybe you want to include this imp into you master?
By the way: Great job with the image so far. Really sad that there is no offical image from sonatype for RPI

**Comment by klo2k** [comment]
Thanks for your contribution Oliver!

Just trying to build the image with this changes but for some reason, Nexus is failing to start, with just this line in `docker logs` + 400% CPU...:
```
OpenJDK Client VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
```

I don't think it's caused by your changes but rather something to do wit the new java runtime...

development build:
```
root@pi4-dev1:/srv/nexus# docker run --rm -it klo2k/nexus3:development bash
nexus@97159d2ced85:/$ java -version
OpenJDK Client VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1ubuntu1-b09)
OpenJDK Client VM (build 25.252-b09, mixed mode)
nexus@97159d2ced85:/$ exit
```

stable release:
```
root@pi4-dev1:/srv/nexus# docker run --rm -it klo2k/nexus3:3.25.0 bash
nexus@f76cfa391e8b:/$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK Client VM (build 25.252-b09, mixed mode)
```

I'm gonna look into this further and squash + merge when I get a build that works.

**Comment by klo2k** [comment]
Sorry for the delay @OliverJurkschat , #4 is causing me headache at the moment - and getting important given the latest release fixes a security vulnerability.

I'll first focus on getting a build working with a straight `docker run` on Raspbian first.

Soon after I will verify your fix.

**Comment by klo2k** [comment]
@OliverJurkschat , thanks for your contribution!

I've tested, merged and included into latest release:
https://github.com/klo2k/nexus3-docker/releases/tag/3.25.1-04

**Comment by OliverJurkschat** [comment]
> @OliverJurkschat , thanks for your contribution!
> 
> I've tested, merged and included into latest release:
> https://github.com/klo2k/nexus3-docker/releases/tag/3.25.1-04

Thanks for including it!! And don't worry about the delay, I am not really fast at the moment...!

**Comment by OliverJurkschat** [comment]
Thanks a lot for including it 👍😊
i now switched to your latest official release and it works as expected for
me.
Cheers, Oliver!

Kok-Yan Lo <notifications@github.com> schrieb am Sa., 1. Aug. 2020, 16:16:

**Pull request closed without merging**
