### PR TITLE
A big improvment

### PR DESCRIPTION
**Pull request by mhkarimi1383**
1. using Debian instead of large and slow ubuntu
2. using wget instead of ADD in docker image (its faster)
3. I got lots of permission denied errors so I'm using default user

### CODE REVIEW

**Comment by klo2k** [comment]
Thanks for the suggestions - I like your idea about using wget to speed up build - will do some testing and get back.

I'll provide more details this / next weekend - it's been busy in my life....

I need to test the latest ubuntu/debian build on raspberry pi to see if https://github.com/klo2k/nexus3-docker/issues/4 also / still exist (which may be why you may be having problem doing `apt update`).

I wouldn't run Nexus as root for security reason.

Thanks, and I'll get back to you.

**Comment by mhkarimi1383** [comment]
this image is up for 3 or 4 days and everything is okay
but i have 8 GB of memory and it using about 30% of that when I'm doing Nothing

**Comment by klo2k** [comment]
@mhkarimi1383 thanks for your ideas and sample code.

I've tweaked the imp. slightly in #13 - and would love for your feedback / testing the new image (`klo2k/nexus3:development`)

The new Nexus version and image seems to work ok for me.

**Comment by klo2k** [comment]
Just FYI I'm gonna merge #13 tomorrow and close this, as the development build has been running fine on my end.

If you have any feedback to #13, please let me know before it's merged.

Thanks for your suggestions and sample code.

**Pull request closed without merging**
